### ISSUE TITLE
질문사항에 대해서

### ISSUE THREAD

**Issue by dolfalf** [ByeongGwan-Seo/Practicing-Swift#7]
공부 또는 연수하시다가 궁금한거 있으면 질문issue로 남겨주세요. 
시간날때마다 답변달아드리겠습니다.

**Comment by gomserker-jp** [comment]
우와... 상세한 답변 감사합니다!
지금 코로나 때문에 상태가 좋지 않지만 낫는대로 열심히 공부해서 많이 물어보도록 하겠습니다.
