### ISSUE TITLE
indexPath에 대한 질문

### ISSUE THREAD

**Issue by gomserker-jp** [ByeongGwan-Seo/Practicing-Swift#8]
https://github.com/ByeongGwan-Seo/Practicing-Swift/blob/c1fe394b256d91e8e18d18a0f8e9a58459c712d7/AppleFramework/AppleFramework/AppleFrameworkViewController.swift#L40-L46   

```
A list of indexes that together represent the path to a specific location in a tree of nested arrays.
```

다른 강의를 보면서 UIKit을 사용한 UI 컴포넌트 배치를 연습하고 있습니다. 그런데 강의에서 indexPath에 대한 설명이 거의 없다시피해서 문의 드립니다.   
애플 공식 문서를 보면 특정 위치에 대한 경로를 나타내는 인덱스의 목록이라고 하는데요, 그럼 44~46행의 경우는,   
```
framework는 

14행의 let list: [AppleFramework] = AppleFramework.list
의 각 내용이 담긴 Array이고, indexPath.item으로 각 요소의 위치를 참조한다.
```
이렇게 이해를 해도 문제가 없을까요?

**Comment by dolfalf** [comment]
indexPath는 UITableView상에서 표시되는 정보를 가지고 있습니다. (section, row) 기본적으로는 배열의 위치랑 맵핑되도록 구현하기에 일단은 그렇게 생각해도 됩니다. (섹션이 하나일경우)
