### ISSUE TITLE
Delegate Pattern 실습 관련 질문입니다.

### ISSUE THREAD

**Issue by gomserker-jp** [ByeongGwan-Seo/Practicing-Swift#9]
보내주신 qiita링크의 코드를 실습해보고 제가 이해한대로 풀어보겠습니다.
잘못된 부분이 있다면 말씀부탁드립니다.

https://github.com/ByeongGwan-Seo/Practicing-Swift/blob/f55f1d33635ae7cfe837c49a1511736e3466f2a0/MyPlayground.playground/Contents.swift#L31-L35

delegate 프로토콜. 위임받았을 때 기능을 수행해야 한다. (학교 어떻게 갈래? 점심 어떻게 할래? 수업 끝나면 뭐할래? 물어봄)

https://github.com/ByeongGwan-Seo/Practicing-Swift/blob/f55f1d33635ae7cfe837c49a1511736e3466f2a0/MyPlayground.playground/Contents.swift#L37-L50

오늘의 남주 역할. 40행에서 (스케쥴 델리게이트 프로토콜을 채용? 상속?) 여자친구가 있니? 라는 질문에 38행에서 "없어요"로 초기화함.
nil로 if문의 조건문에 false이므로 delegate 되지 않고 print문이 출력됨

https://github.com/ByeongGwan-Seo/Practicing-Swift/blob/f55f1d33635ae7cfe837c49a1511736e3466f2a0/MyPlayground.playground/Contents.swift#L52-L62

여친 역할. ScheduleDelegate 프로토콜을 상속. 질문(gotoSchool() 등)에 대한 결정을 위임받은 위임자.(Delegate)
남주의 질문에 대답.   (학교 어떻게 갈래? -> 같이 지하철 타자, 점심 어떡할래? -> 같이 먹자, 수업 끝나면 뭐할래? -> 극장 가자) 

https://github.com/ByeongGwan-Seo/Practicing-Swift/blob/f55f1d33635ae7cfe837c49a1511736e3466f2a0/MyPlayground.playground/Contents.swift#L64-L65

변수 namJu와 girl 은 각각 남주와 여친 역할을 수행한다.

https://github.com/ByeongGwan-Seo/Practicing-Swift/blob/f55f1d33635ae7cfe837c49a1511736e3466f2a0/MyPlayground.playground/Contents.swift#L67-L71

69행에서 40행에서 여자친구가 있냐는 질문에 있다고 대답함. 위임자가 있으므로 delegate 프로토콜이 돌아감.   

result
```
without gf
bicycle alone
alone eat
going home alone
with gf
together subway
eat together
go to theater
```

**Comment by dolfalf** [comment]
잘 이해하신것 같습니다. 두 클래스간에 딜리게이트패턴으로 데이타를 주고 받았다는것이 포인트 입니다.  
이제 UITableView 또는 CollectionView 를 잘 보시면 어떻게 데이타를 주고받는지가 보일거예요. ^^

**Comment by gomserker-jp** [comment]
주말 늦은 시간에 답변 감사합니다ㅜㅜ
단순히 강의 따라 치는게 아니라 어떻게 움직이는지 코드를 좀 뜯어보면서 더 이해해 보도록 하겠습니다.
